### ISSUE TITLE
False suggestion to add  "roave/security-advisories": "dev-master"

### ISSUE THREAD

**Issue by neorganic** [kalessil/phpinspectionsea#867]
I have  "roave/security-advisories": "dev-master" in require-dev, but the inspection seems to ignore that an even more it advises to add it to the "required", when the official "roave/security-advisories" documentation is real clear about this.

**Comment by bcremer** [comment]
This was fixed in https://github.com/kalessil/phpinspectionsea/issues/830.
The Version containing this fix was released a few days ago.

**Comment by kalessil** [comment]
@neorganic : would you please confirm if the plugin update has fixed the issue?

**Comment by neorganic** [comment]
@kalessil Yes, I can confirm this is resolved! :+1:

**Comment by internalsystemerror** [comment]
If not using require-dev ... this problem still occurs (see: https://github.com/internalsystemerror/php-metapackage-development/blob/master/composer.json)

**Comment by internalsystemerror** [comment]
@kalessil i dnt like to reopen old issues, but this seems directly related. Pls advise whether this should be a new issue or whether this one can be reused?

**Comment by internalsystemerror** [comment]
@kalessil thanks for the clarification. In which case the bug is that the inspection repeatedly adds the package to require and not require-dev. If you check that composer.json in the current PhpStorm you will see the issue.

Personally from reading through the discussions it seems that required-dev should be where the package is added when allowing the inspection to autofix (at the moment this is require), and that as long as the package is added to either require or require-dev, the inspection should not show a warning. If I've misunderstood that, the autofix problem still remains either way.

**Comment by bcremer** [comment]
@kalessil I was able to reproduce the error described by @internalsystemerror. This only happens if no `require-dev` is yet present in the composer.json

![image](https://user-images.githubusercontent.com/55820/57354335-7c28d180-716b-11e9-9bec-a8adfcf170b8.png)

![image](https://user-images.githubusercontent.com/55820/57354375-95ca1900-716b-11e9-97ea-42f87ebf70e8.png)

The quick-fix also only works if a require-dev section is already available. Else it will add the `advisories` package to the `require` section and complain afterwards that it should be placed in `require-dev`.

Hope this helps.

**Comment by kalessil** [comment]
@internalsystemerror, @bcremer: understood now, filed a new issue - #1324
